name: Lego Kontrol
on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir çalış
  workflow_dispatch: # Manuel çalıştırma butonu ekler
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Paketleri Yukle
        run: pip install -r requirements.txt
      - name: Botu Calistir
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
